### ISSUE TITLE
Gravatar link update for faster loading time

### ISSUE THREAD

**Issue by kmAyush** [RECursion-NITD/RECursionNITD-website#105]
Presently, the gravatar link we are using loads image of (400 x 400) size but the image size we need to display is (55 x 55) . There is a better link for gravatar which allows us to set image size.

Current Gravatar link  - 
https://api.adorable.io/avatars/ ( RANDOM NUMBER )
Example - https://api.adorable.io/avatars/65

Updated Gravatar link -
https://api.adorable.io/avatars/ ( IMAGE SIZE )/( RANDOM NUMBER/UNIQUE VALUE ).png
Example - [https://api.adorable.io/avatars/65/ayush1234.png](https://api.adorable.io/avatars/65/ayush1234.png) 
 
Image size for (400 x 400) - 21 kb
Image size for (65 x 65) - 5 kb  
AskREC page requires to load the list of 154 questions and that many gravatar images right now.

**Comment by ash1969** [comment]
Well Done Team
