### ISSUE TITLE
Email Case Sensitivity

### ISSUE THREAD

**Issue by sharshach** [RECursion-NITD/RECursionNITD-website#127]
check email case-sensitivity while registering a new user.

Current : 
- suppose my email id is example@email.com
- Now I am able to register different accounts with 
  - example@email.com
  - Example@email.com
  - EXAMPLE@EMAIL.com
  - ExeMplE@email.com
- etc... so a user can login with same  email for more than 1 account

Update to be Made: change email to lower case and verify then

-> verification is alredy done just make sure to keep all data in lower case

**Comment by arin17bishwa** [comment]
working on it vaiya

**Comment by iamskab** [comment]
Completed!
