### ISSUE TITLE
markdown issues

### ISSUE THREAD

**Issue by sharshach** [RECursion-NITD/RECursionNITD-website#129]
markdown is not working while we are pasting codes

**Comment by vishvanath45** [comment]
@sharshach  Can you tell, what Markdown formatting you were using?

From last time I recall, we had to add "```" at beginning and end of code block for markdown to render properly. :D

**Comment by sharshach** [comment]
@vishvanath45  Now also we are using the same.
But there are some errors in it like if we use #include in a code block then include is turning as a heading which is not assumed to happen.
![image](https://user-images.githubusercontent.com/48358526/102709546-ca9fcb00-42d1-11eb-915f-a944fabe760c.png)
