### ISSUE TITLE
Search User By Name

### ISSUE THREAD

**Issue by ash1969** [RECursion-NITD/RECursionNITD-website#138]
Feature to search user by name (Kind of Stopstalk)

**Comment by arin17bishwa** [comment]
Started working on it.

Have already prepared a view to support this search function using "filter(name__icontains=query)" filter.

But there will be some problems in partial matches. For example, searching for "td" will return an empty queryset even if I have an user named "ted".

**Comment by ash1969** [comment]
@arin17bishwa Try to implement a view similar to what we are using to search questions, posts, and interview experiences!

**Comment by iamskab** [comment]
Completed !
