### ISSUE TITLE
Blog Update Errors

### ISSUE THREAD

**Issue by sharshach** [RECursion-NITD/RECursionNITD-website#141]
let blog is written 

And it is updated once

And updated again

And now suppose if we try to update again we are getting the 1st updated version to edit and not the latest update.

I faced this issue when editing some others post as admin
kindly check all possibilities too

**Comment by SubhamGupta007** [comment]
No error found while updating the blog post , the problem might be due to some other circumstances

**Comment by harshitsurana** [comment]
Issue non-reproducible. If a similar issue is received in feedback, will raise another issue.
