### ISSUE TITLE
Admin updatng issues

### ISSUE THREAD

**Issue by sharshach** [RECursion-NITD/RECursionNITD-website#142]
if Admin is updating some thing 

askrec problem or blog or (check other places too)

the author name is changing to the admin

And main problem is the owner of blog/askrec problem author is losing his update access to their blog/askrec.

**Comment by arin17bishwa** [comment]
Bhaiya, I tried reproducing this bug, but I couldn't.

Changing any information in AskREC or Blog post did not change the creator ID(unless we manually change the creator field itself).

**Comment by sharshach** [comment]
[https://recursionnitd.in/forum/detail/154/](https://recursionnitd.in/forum/detail/154/)

![image](https://user-images.githubusercontent.com/48358526/119917466-40e0e180-bf84-11eb-9bff-5d5bb939ec99.png)

![image](https://user-images.githubusercontent.com/48358526/119917525-5b1abf80-bf84-11eb-84fe-2b48f451ea20.png)

![image](https://user-images.githubusercontent.com/48358526/119917590-7d144200-bf84-11eb-8116-7598c82e5f45.png)


Now check 
- if you are getting access to update this question
- If you didn't get access we need to work on that
- if you get access we need to change the name which is getting displayed

**Comment by arin17bishwa** [comment]
Ok bhaiya, understood.

I lost the edit access.

**Comment by iamskab** [comment]
Completed !
