### ISSUE TITLE
WYSIWYG (add feuture)

### ISSUE THREAD

**Issue by sharshach** [RECursion-NITD/RECursionNITD-website#144]
if possible add WYSIWYG editor in place of current markdown editor.
It will enhances the user experience at every part of website.

**Comment by kmAyush** [comment]
WYSIWYG editor are simple and easy-to-use but it does not save text as text that will restrict our adaptability to any different tech. There are few other issues, one may read it from here -  
https://dev.to/practicalprogramming/advantages-of-document-markup-languages-vs-wysiwyg-editors-9f6. 
Like github or gitter uses markdowns. I guess what we can do is bring markdown help/guide thing in user's focus while he writes.

**Comment by sharshach** [comment]
> WYSIWYG editor are simple and easy-to-use but it does not save text as text that will restrict our adaptability to any different tech. There are few other issues, one may read it from here -
> https://dev.to/practicalprogramming/advantages-of-document-markup-languages-vs-wysiwyg-editors-9f6.
> Like github or gitter uses markdowns. I guess what we can do is bring markdown help/guide thing in user's focus while he writes.

👍
