### ISSUE TITLE
Sign In with Google do not redirects to last visited page

### ISSUE THREAD

**Issue by harshitsurana** [RECursion-NITD/RECursionNITD-website#161]
1. Sign In with Google Redirects to the default login redirect URL that is for the home page instead of the last page for which login was required.
2. This issue can be experienced after signing out and visiting any of these URLs for example ([Interview Experience](http://recursionnitd.in/experience/), [Post Question](https://recursionnitd.in/forum/add))

**Comment by iamskab** [comment]
Completed!
