### ISSUE TITLE
Add Image generator like gravatar for account sign up 

### ISSUE THREAD

**Issue by kmAyush** [RECursion-NITD/RECursionNITD-website#21]
While account sign up, image generator can be used, like used in Github.

**Comment by kmAyush** [comment]
`"https://api.adorable.io/avatars/" +  randomNumber`
This can be user profile picture in case user does not provide any.

**Comment by vishvanath45** [comment]
@ash1969 remove the current option of putting image link, add an upload image option, make it optional, in case user does not put anything, use the adorable api to generate random image.

**Comment by ash1969** [comment]
Completed
