### ISSUE TITLE
setup nginx to handle all static files

### ISSUE THREAD

**Issue by vjs22334** [RECursion-NITD/RECursionNITD-website#58]
ATM nginx only serves static files if static is in the request url.
we need to chenge this rule to include all static files paths.
we can use [whitenoise](http://whitenoise.evans.io/en/stable/).

**Comment by vishvanath45** [comment]
SO discussion over [here](https://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail)

I believe using whitenoise(as given in answers) would fix this problem.

**Comment by ash1969** [comment]
Done! Nginx set up to serve all static and media files!
