### ISSUE TITLE
Image link seems broken

### ISSUE THREAD

**Issue by vishvanath45** [RECursion-NITD/RECursionNITD-website#72]
Image for `Batch 2018-19` people seems broken. 
![Screenshot_2019-09-01 https recursionnitd in](https://user-images.githubusercontent.com/16117380/64078300-9a0bda80-ccf6-11e9-9cd3-5a532674e473.png)

cc - @kmAyush  @piedpipr

**Comment by kmAyush** [comment]
It is an issue of either File format mismatch or pictures in wrong folder as told by @piedpipr . He was involved in updating team page. We will fix this issue soon.
