### ISSUE TITLE
add user profile

### ISSUE THREAD

**Issue by vjs22334** [RECursion-NITD/RECursionNITD-website#8]
add functionality for displaying and editing a user profile with necessary views and templates. users should only be able to edit their own profiles. also provide option to change password. refer to the profile model for the necessary fields.

**Comment by vishvanath45** [comment]
- Remove email from User Profile.
- Make Email mandatory while registering. 
- Remove nickname from profile. 
- Logged in user, if wants to register, should be redirected to edit profile.  
- Notify Username already exists. [AJAX]

**Comment by vishvanath45** [comment]
Done
