### ISSUE TITLE
Upcoming event detail is not showing in format.

### ISSUE THREAD

**Issue by kmAyush** [RECursion-NITD/RECursionNITD-website#91]
Upcoming event detail that is shown on the top right of homepage is not showing in the formatted way as the input text. 
Possible solution - Markdown can be implemented.
![WhatsApp Image 2019-10-31 at 7 35 32 PM](https://user-images.githubusercontent.com/36049076/68453957-105c1a00-021d-11ea-825e-e53db61f5bd8.jpeg)

**Comment by Prakhar19999** [comment]
Instead of Calendar view can we can have the view like hackerearth page
